import React, { useEffect, useState } from 'react';
import BusinessLocationSelect from './BusinessLocationSelect';
import { paymentAccountService } from '../services/apiService';
import { formatCurrency, formatDate } from '../context/BusinessSettingsContext';

const money = (value) => formatCurrency(value);
const dateText = (value) => value ? formatDate(value) : '-';

export default function PaymentReportView({ mode }) {
  const [report, setReport] = useState(null);
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [location, setLocation] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { setReport(await paymentAccountService.getReport({ fromDate: fromDate || undefined, toDate: toDate || undefined, location: location || undefined })); } catch (e) { setError(e.response?.data?.message || 'Failed to load financial report'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const title = mode === 'balance' ? 'Balance Sheet' : mode === 'trial' ? 'Trial Balance' : mode === 'cash' ? 'Cash Flow Statement' : 'Payment Account Report';
  const apply = (e) => { e.preventDefault(); load(); };
  if (loading && !report) return <div className="p-6">Loading {title}...</div>;
  return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-800">{title}</h1><p className="mt-2 text-gray-600">Calculated from current sales, purchases, expenses, inventory, and payment accounts</p></div>{error && <div className="mb-4 rounded bg-red-50 p-3 text-red-700">{error}</div>}<form onSubmit={apply} className="mb-6 flex flex-wrap gap-2 rounded-lg bg-white p-4 shadow"><input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="rounded border px-3 py-2" /><input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="rounded border px-3 py-2" /><BusinessLocationSelect value={location} onChange={(e) => setLocation(e.target.value)} allLabel="All Locations" className="rounded border px-3 py-2" /><button className="rounded bg-teal-600 px-4 py-2 text-white">Generate Report</button></form>
    {mode === 'balance' && <div className="grid grid-cols-1 gap-6 md:grid-cols-2"><section className="rounded-lg bg-white p-6 shadow"><h2 className="mb-4 border-b pb-2 text-xl font-bold">Assets</h2><ReportLine label="Cash and Payment Accounts" value={report.totalBalance} /><ReportLine label="Inventory" value={report.inventoryValue} /><ReportLine label="Total Assets" value={Number(report.totalBalance || 0) + Number(report.inventoryValue || 0)} strong /></section><section className="rounded-lg bg-white p-6 shadow"><h2 className="mb-4 border-b pb-2 text-xl font-bold">Liabilities & Equity</h2><ReportLine label="Accounts Payable" value={report.accountsPayable} /><ReportLine label="Net Trading Position" value={Number(report.totalSales || 0) - Number(report.totalPurchases || 0) - Number(report.totalExpenses || 0)} /><ReportLine label="Total Liabilities & Equity" value={Number(report.accountsPayable || 0) + Number(report.totalSales || 0) - Number(report.totalPurchases || 0) - Number(report.totalExpenses || 0)} strong /></section></div>}
    {mode === 'cash' && <div className="rounded-lg bg-white p-6 shadow"><h2 className="mb-5 text-lg font-semibold">Cash Flow Statement</h2><ReportLine label="Cash from Operating Activities" value={report.netCashFromOperating} /><ReportLine label="Cash from Investing Activities" value={report.netCashFromInvesting} /><ReportLine label="Cash from Financing Activities" value={report.netCashFromFinancing} /><ReportLine label="Net Increase in Cash" value={Number(report.netCashFromOperating || 0) + Number(report.netCashFromInvesting || 0) + Number(report.netCashFromFinancing || 0)} strong /><ReportLine label="Cash at End of Period" value={report.closingBalance} strong /></div>}
    {mode === 'trial' && <div className="overflow-x-auto rounded-lg bg-white p-6 shadow"><h2 className="mb-4 text-lg font-semibold">Trial Balance</h2><table className="min-w-full divide-y"><thead><tr>{['Code','Account','Debit','Credit'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs uppercase text-gray-500">{h}</th>)}</tr></thead><tbody>{(report.trialBalance || []).map((row) => <tr key={row.code}><td className="px-4 py-3">{row.code}</td><td className="px-4 py-3">{row.account}</td><td className="px-4 py-3">{money(row.debit)}</td><td className="px-4 py-3">{money(row.credit)}</td></tr>)}</tbody></table></div>}
    {mode === 'report' && <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-4"><Card label="Opening Balance" value={report.openingBalance} /><Card label="Receipts" value={report.totalReceipts} /><Card label="Payments" value={report.totalPayments} /><Card label="Closing Balance" value={report.closingBalance} /></div>}
    {(mode === 'report' || mode === 'cash') && <div className="mt-6 overflow-x-auto rounded-lg bg-white p-6 shadow"><h2 className="mb-4 text-lg font-semibold">Transactions</h2><table className="min-w-full divide-y"><thead><tr>{['Date','Account','Type','Reference','Description','Debit','Credit','Balance'].map((h) => <th key={h} className="px-3 py-3 text-left text-xs uppercase text-gray-500">{h}</th>)}</tr></thead><tbody>{(report.transactions || []).map((row, index) => <tr key={`${row.reference}-${index}`}><td className="px-3 py-3">{dateText(row.date)}</td><td className="px-3 py-3">{row.account}</td><td className="px-3 py-3">{row.type}</td><td className="px-3 py-3">{row.reference}</td><td className="px-3 py-3">{row.description}</td><td className="px-3 py-3">{money(row.debit)}</td><td className="px-3 py-3">{money(row.credit)}</td><td className="px-3 py-3 font-semibold">{money(row.balance)}</td></tr>)}</tbody></table>{!report.transactions?.length && <p className="p-5 text-center text-gray-500">No transactions found for this period.</p>}</div>}
  </div>;
}
function ReportLine({ label, value, strong }) { return <div className={`flex justify-between border-b py-3 ${strong ? 'font-bold text-teal-700' : ''}`}><span>{label}</span><span>{money(value)}</span></div>; }
function Card({ label, value }) { return <div className="rounded-lg bg-teal-600 p-5 text-white"><div className="text-sm opacity-90">{label}</div><div className="text-2xl font-bold">{money(value)}</div></div>; }
