import React, { useEffect, useState } from 'react';
import { settingsService } from '../services/apiService';
import { persistBusinessSettings } from '../context/BusinessSettingsContext';

const defaults = { businessName: '', currency: 'LKR', timeZone: 'Asia/Colombo', fiscalYearStart: 'January', phone: '', email: '', website: '', address: '', automaticInventoryTracking: true, lowStockAlerts: true, emailNotifications: true, multiCurrency: false, invoicePrefix: 'INV-', invoiceStartingNumber: 1001, invoiceTemplate: 'Default Template', paymentTerms: 'Due on Receipt', invoiceHeaderText: '', invoiceFooterText: '', invoiceTerms: '', showCompanyLogo: true, showTaxBreakdown: true, showPaymentInstructions: false, showQrCode: true, autoSendInvoice: false, barcodeType: 'Code 128', barcodePrefix: '', paperSize: 'A4', labelsPerSheet: 12, barcodeHeight: 30, barcodeWidth: 50, showProductName: true, showProductCode: true, showPrice: true, showBusinessName: false, showBusinessLogo: false };
const fields = { business: [['businessName', 'Business Name'], ['currency', 'Currency'], ['timeZone', 'Time Zone'], ['fiscalYearStart', 'Fiscal Year Start'], ['phone', 'Phone Number'], ['email', 'Email'], ['website', 'Website'], ['address', 'Address']], invoice: [['invoicePrefix', 'Invoice Prefix'], ['invoiceStartingNumber', 'Starting Number'], ['invoiceTemplate', 'Invoice Template'], ['paymentTerms', 'Default Payment Terms'], ['invoiceHeaderText', 'Invoice Header Text'], ['invoiceFooterText', 'Invoice Footer Text'], ['invoiceTerms', 'Terms & Conditions']], barcode: [['barcodeType', 'Barcode Type'], ['barcodePrefix', 'Barcode Prefix'], ['paperSize', 'Paper Size'], ['labelsPerSheet', 'Labels Per Sheet'], ['barcodeHeight', 'Barcode Height (mm)'], ['barcodeWidth', 'Barcode Width (mm)']] };
const options = { currency: [{ value: 'LKR', label: 'LKR (Rs)' }, { value: 'USD', label: 'USD ($)' }, { value: 'EUR', label: 'EUR (€)' }, { value: 'GBP', label: 'GBP (£)' }, { value: 'INR', label: 'INR (Rs)' }, { value: 'AUD', label: 'AUD ($)' }, { value: 'CAD', label: 'CAD ($)' }, { value: 'SGD', label: 'SGD ($)' }, { value: 'JPY', label: 'JPY (¥)' }, { value: 'CNY', label: 'CNY (¥)' }, { value: 'AED', label: 'AED' }, { value: 'SAR', label: 'SAR' }], timeZone: [{ value: 'Asia/Colombo', label: 'Sri Lanka (Asia/Colombo)' }, { value: 'UTC', label: 'UTC' }, { value: 'Asia/Kolkata', label: 'India (Asia/Kolkata)' }, { value: 'Asia/Dubai', label: 'United Arab Emirates (Asia/Dubai)' }, { value: 'Asia/Singapore', label: 'Singapore (Asia/Singapore)' }, { value: 'Europe/London', label: 'United Kingdom (Europe/London)' }, { value: 'Europe/Paris', label: 'Central Europe (Europe/Paris)' }, { value: 'America/New_York', label: 'Eastern Time (America/New_York)' }, { value: 'America/Los_Angeles', label: 'Pacific Time (America/Los_Angeles)' }, { value: 'Australia/Sydney', label: 'Australia (Australia/Sydney)' }], fiscalYearStart: ['January', 'April', 'July', 'October'], invoiceTemplate: ['Default Template', 'Modern Template', 'Classic Template', 'Minimal Template'], paymentTerms: ['Due on Receipt', 'Net 15 Days', 'Net 30 Days', 'Net 60 Days'], barcodeType: ['Code 128', 'Code 39', 'EAN-13', 'UPC-A', 'QR Code'], paperSize: ['A4', 'Letter', 'Label 40mm x 30mm', 'Label 50mm x 25mm'], labelsPerSheet: [{ value: 12, label: '12 labels per sheet' }, { value: 24, label: '24 labels per sheet' }, { value: 40, label: '40 labels per sheet' }, { value: 65, label: '65 labels per sheet' }] };

const normalizeProfile = (value = {}) => ({ ...defaults, ...value, labelsPerSheet: Number(value.labelsPerSheet) || defaults.labelsPerSheet });

export default function SettingsProfileEditor({ section, title, description }) {
  const [data, setData] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { settingsService.getProfile().then((value) => { const profile = normalizeProfile(value); setData(profile); persistBusinessSettings(profile); }).catch((error) => setMessage(error.response?.data?.message || 'Failed to load settings')).finally(() => setLoading(false)); }, []);
  const change = (name, value) => setData((current) => ({ ...current, [name]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); try { const saved = await settingsService.saveProfile(data); const profile = normalizeProfile(saved); setData(profile); persistBusinessSettings(profile); setMessage('Settings saved successfully.'); } catch (error) { setMessage(error.response?.data?.message || 'Failed to save settings'); } finally { setSaving(false); } };
  if (loading) return <div className="p-6 text-gray-500">Loading settings...</div>;
  const checks = section === 'business' ? [['automaticInventoryTracking', 'Enable automatic inventory tracking'], ['lowStockAlerts', 'Send low stock alerts'], ['emailNotifications', 'Enable email notifications'], ['multiCurrency', 'Enable multi-currency support']] : section === 'invoice' ? [['showCompanyLogo', 'Show company logo'], ['showTaxBreakdown', 'Show tax breakdown'], ['showPaymentInstructions', 'Show payment instructions'], ['showQrCode', 'Show QR code'], ['autoSendInvoice', 'Auto-send invoice']] : [['showProductName', 'Show product name'], ['showProductCode', 'Show product code/SKU'], ['showPrice', 'Show price'], ['showBusinessName', 'Show business name'], ['showBusinessLogo', 'Show business logo']];
  return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-800">{title}</h1><p className="mt-2 text-gray-600">{description}</p></div>{message && <div className="mb-4 rounded-lg border border-teal-200 bg-teal-50 px-4 py-3 text-teal-800">{message}</div>}<form onSubmit={save} className="space-y-6 rounded-lg bg-white p-6 shadow-md"><div className="grid grid-cols-1 gap-6 md:grid-cols-2">{fields[section].map(([name, label]) => <div key={name} className={['address', 'invoiceFooterText', 'invoiceTerms'].includes(name) ? 'md:col-span-2' : ''}><label className="mb-2 block text-sm font-medium text-gray-700">{label}</label>{options[name] ? <select value={data[name] ?? ''} onChange={(e) => change(name, name === 'labelsPerSheet' ? Number(e.target.value) : e.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-2">{options[name].map((option) => { const value = typeof option === 'string' ? option : option.value; const label = typeof option === 'string' ? String(option) : option.label; return <option key={value} value={value}>{label}</option>; })}</select> : ['address', 'invoiceFooterText', 'invoiceTerms'].includes(name) ? <textarea rows="3" value={data[name] || ''} onChange={(e) => change(name, e.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-2" /> : <input type={['invoiceStartingNumber', 'labelsPerSheet', 'barcodeHeight', 'barcodeWidth'].includes(name) ? 'number' : name === 'email' ? 'email' : 'text'} value={data[name] ?? ''} onChange={(e) => change(name, ['invoiceStartingNumber', 'labelsPerSheet', 'barcodeHeight', 'barcodeWidth'].includes(name) ? Number(e.target.value) : e.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-2" />}</div>)}</div><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{checks.map(([name, label]) => <label key={name} className="flex items-center gap-3"><input type="checkbox" checked={Boolean(data[name])} onChange={(e) => change(name, e.target.checked)} className="h-4 w-4" /><span className="text-sm text-gray-700">{label}</span></label>)}</div><button disabled={saving} className="rounded-lg bg-teal-600 px-6 py-2 text-white hover:bg-teal-700 disabled:bg-gray-400">{saving ? 'Saving...' : 'Save Settings'}</button></form></div>;
}