import React, { useEffect, useState } from 'react';
import BusinessLocationSelect from '../../components/BusinessLocationSelect';
import { businessLocationService, settingsService } from '../../services/apiService';

const empty = { name: '', printerType: 'Thermal Printer', connectionType: 'USB', connectionValue: '', paperWidth: '80mm', locationId: '' };
export default function ReceiptPrinters() {
  const [printers, setPrinters] = useState([]); const [form, setForm] = useState(empty); const [locations, setLocations] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setPrinters(await settingsService.getPrinters()); } catch (e) { setError(e.response?.data?.message || 'Failed to load printers'); } finally { setLoading(false); } };
  useEffect(() => { load(); businessLocationService.getAll().then(setLocations).catch(() => setLocations([])); }, []);
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const location = locations.find((item) => String(item.id) === String(form.locationId) || item.name === form.locationId); await settingsService.savePrinter({ ...form, locationId: location?.id || null }); setForm(empty); await load(); } catch (err) { setError(err.response?.data?.message || 'Failed to save printer'); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm('Delete this printer?')) return; try { await settingsService.deletePrinter(id); await load(); } catch (e) { setError(e.response?.data?.message || 'Failed to delete printer'); } };
  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-800">Receipt Printers</h1><p className="mt-2 text-gray-600">Configure receipt printers for POS system</p></div>{error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>}<div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><form onSubmit={submit} className="space-y-4 rounded-lg bg-white p-6 shadow-md"><h2 className="text-lg font-semibold text-gray-800">{form.id ? 'Edit Printer' : 'Add New Printer'}</h2>{[['name', 'Printer Name'], ['connectionValue', 'IP Address / Port']].map(([name, label]) => <div key={name}><label className="mb-2 block text-sm font-medium text-gray-700">{label}</label><input name={name} value={form[name]} onChange={change} required={name === 'name'} className="w-full rounded-lg border border-gray-300 px-4 py-2" /></div>)}{[['printerType', ['Thermal Printer', 'Dot Matrix', 'Laser Printer', 'Inkjet Printer']], ['connectionType', ['USB', 'Network (IP Address)', 'Bluetooth', 'Serial Port']], ['paperWidth', ['58mm', '80mm', '110mm']]].map(([name, values]) => <select key={name} name={name} value={form[name]} onChange={change} className="w-full rounded-lg border border-gray-300 px-4 py-2">{values.map((value) => <option key={value}>{value}</option>)}</select>)}<BusinessLocationSelect value={form.locationId} onChange={(e) => setForm({ ...form, locationId: e.target.value })} /><button disabled={saving} className="w-full rounded-lg bg-teal-600 px-4 py-2 text-white disabled:bg-gray-400">{saving ? 'Saving...' : 'Save Printer'}</button></form><div className="rounded-lg bg-white p-6 shadow-md"><h2 className="mb-4 text-lg font-semibold text-gray-800">Configured Printers</h2>{loading ? <p>Loading printers...</p> : printers.length === 0 ? <p className="text-gray-500">No printers configured.</p> : <div className="space-y-3">{printers.map((printer) => <div key={printer.id} className="rounded-lg border border-gray-200 p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{printer.name}</h3><p className="text-sm text-gray-600">{printer.printerType} · {printer.connectionType} {printer.connectionValue && `(${printer.connectionValue})`}</p><p className="text-sm text-gray-600">Paper: {printer.paperWidth}</p></div><div className="flex gap-2 text-sm"><button onClick={() => setForm(printer)} className="text-blue-600">Edit</button><button onClick={() => remove(printer.id)} className="text-red-600">Delete</button></div></div></div>)}</div>}</div></div></div>;
}
