import React, { useEffect, useState } from 'react';
import { settingsService } from '../../services/apiService';

const empty = { name: '', rate: '', taxType: 'VAT', taxNumber: '', defaultRate: false };
export default function TaxRates() {
  const [rates, setRates] = useState([]); const [form, setForm] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setRates(await settingsService.getTaxRates()); } catch (e) { setError(e.response?.data?.message || 'Failed to load tax rates'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { await settingsService.saveTaxRate({ ...form, rate: Number(form.rate) }); setForm(empty); await load(); } catch (err) { setError(err.response?.data?.message || 'Failed to save tax rate'); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm('Delete this tax rate?')) return; try { await settingsService.deleteTaxRate(id); await load(); } catch (e) { setError(e.response?.data?.message || 'Failed to delete tax rate'); } };
  return <div className="p-6"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-800">Tax Rates</h1><p className="mt-2 text-gray-600">Manage tax rates and tax groups</p></div>{error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-red-700">{error}</div>}<div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><form onSubmit={submit} className="space-y-4 rounded-lg bg-white p-6 shadow-md"><h2 className="text-lg font-semibold text-gray-800">{form.id ? 'Edit Tax Rate' : 'Add New Tax Rate'}</h2><input required placeholder="Tax Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full rounded-lg border border-gray-300 px-4 py-2" /><input required type="number" min="0" max="100" step="0.01" placeholder="Tax Rate (%)" value={form.rate} onChange={(e) => setForm({ ...form, rate: e.target.value })} className="w-full rounded-lg border border-gray-300 px-4 py-2" /><select value={form.taxType} onChange={(e) => setForm({ ...form, taxType: e.target.value })} className="w-full rounded-lg border border-gray-300 px-4 py-2"><option>VAT</option><option>GST</option><option>Sales Tax</option><option>Excise Tax</option><option>Custom Tax</option></select><input placeholder="Tax registration number" value={form.taxNumber} onChange={(e) => setForm({ ...form, taxNumber: e.target.value })} className="w-full rounded-lg border border-gray-300 px-4 py-2" /><label className="flex items-center gap-3"><input type="checkbox" checked={form.defaultRate} onChange={(e) => setForm({ ...form, defaultRate: e.target.checked })} /><span>Set as default tax rate</span></label><button disabled={saving} className="w-full rounded-lg bg-teal-600 px-4 py-2 text-white disabled:bg-gray-400">{saving ? 'Saving...' : 'Save Tax Rate'}</button></form><div className="rounded-lg bg-white p-6 shadow-md"><h2 className="mb-4 text-lg font-semibold text-gray-800">Existing Tax Rates</h2>{loading ? <p>Loading tax rates...</p> : rates.length === 0 ? <p className="text-gray-500">No tax rates configured.</p> : <div className="space-y-3">{rates.map((rate) => <div key={rate.id} className="rounded-lg border border-gray-200 p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{rate.name} ({Number(rate.rate).toFixed(2)}%)</h3><p className="text-sm text-gray-600">{rate.taxType}{rate.taxNumber ? ` · ${rate.taxNumber}` : ''}</p>{rate.defaultRate && <span className="text-xs text-teal-700">Default</span>}</div><div className="flex gap-2 text-sm"><button onClick={() => setForm(rate)} className="text-blue-600">Edit</button><button onClick={() => remove(rate.id)} className="text-red-600">Delete</button></div></div></div>)}</div>}</div></div></div>;
}
